/* $Id: 2018-09-28 03:17:38 $
 * 
 * This file is auto-generated by parser, DO NOT MODIFY! 
 * Copyright (c) 2014-2018 Zerone.IO. All rights reserved.
 *
 */

#pragma once

#include "JsonUtils.h"


/**
 * from_json
 * Parsing from json object to C object
 */
template<typename T>
int from_json(JsonUtils::Json &json, T &v);

/**
 * to_json
 * Serialize from C object to json string
 */
template<typename T>
std::string to_json(const T &v);

