/* $Id: 2018-09-16 19:09:08 $
 * 
 * This file is auto-generated by parser, DO NOT MODIFY! 
 * Copyright (c) 2014-2018 Zerone.IO. All rights reserved.
 * 
 */

#include "json_decoder.h"
#include "json2c.inc"

